### ISSUE TITLE
Fix any type

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#122]
Better type casting for `any` types

**Comment by mozartfish** [comment]
@waxlamp @JackWilb I started fixing types with this commit but I think it might take me some time later to fix this. I was wondering if you have any suggestions for how we can clear up this type issue with any. https://github.com/multinet-app/multimatrix/pull/120/commits/93635430ec6945c343d0088958df0cf94f5405e7

**Comment by waxlamp** [comment]
Are there still any `any`s left in your PR branch?

**Comment by waxlamp** [comment]
@mozartfish you closed this without answering my question above--is this really resolved?
