### ISSUE TITLE
Use map()

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#124]
I think this would be better off with a `map()` call. Something like this (please verify that this works):

```suggestion
  const newNodes: any[] = nodes.map((node) => {
    const newNode = {
      ...node,
    };

    // remove the properties that will not be used
    // and properties that will be recalculated for visualization
    delete newNode.neighbors;

    return newNode;
  });
```

_Originally posted by @waxlamp in https://github.com/multinet-app/multimatrix/pull/120#r521495033_

**Comment by mozartfish** [comment]
@gotdairyya @waxlamp this change request has been addressed with this commit https://github.com/multinet-app/multimatrix/pull/120/commits/1e5ddce670f8bfa2e37c7687bbcb1e52492b0c16

**Comment by mozartfish** [comment]
this issue was not resolved properly as described in this comment. https://github.com/multinet-app/multimatrix/pull/159#discussion_r556202948

**Comment by mozartfish** [comment]
issue is addressed with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/b4b1a942ae28dbd8361c35f0ed522fee0d9a9881
