### ISSUE TITLE
Create table for node attributes

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#125]
Instead of calling `.find()` on the super node list repeatedly (which makes this run in O(N^2)) it is probably better to construct a table that maps from attribute name to the super node representing it, then use that to perform the lookup here.

_Originally posted by @waxlamp in https://github.com/multinet-app/multimatrix/pull/120#r521500680_

**Comment by mozartfish** [comment]
@waxlamp @gotdairyya this request has been addressed by this commit https://github.com/multinet-app/multimatrix/pull/120/commits/7bf16b49a606991f60c0c22c609524e83b0bb4c8

**Comment by waxlamp** [comment]
If you edit your PR's description field to include the phrase "Closes #125", then when your PR is merged, this issue will be closed automatically.

If you have other issues that were addressed by your changes, please include a "closes" statement for those as well.

**Comment by JackWilb** [comment]
@mozartfish Please close this if it's been fixed and reference the pull request that fixes it with #<PR number>
