### ISSUE TITLE
Disconnected Supernodes

### ISSUE THREAD

**Issue by mozartfish** [multinet-app/multimatrix#128]
Currently all the datasets we have are connected for supernode aggregation and all nodes that do not have any neighbors (nodes, supernodes) are removed if they have no neighbors. This causes a potential issue when we have a disconnected supernode such as in this particular case.

_Originally posted by @waxlamp in https://github.com/multinet-app/multimatrix/pull/120#discussion_r521503927_

**Comment by JackWilb** [comment]
https://github.com/multinet-app/multimatrix/pull/159#discussion_r556204568
