### ISSUE TITLE
Implementing Sorting for Supergraph Nodes

### ISSUE THREAD

**Issue by mozartfish** [multinet-app/multimatrix#129]
Sorting is a data wrangling operation that was discussed in Origraph, Graffinity, and the State of the Art Report on Multivariate Networks but hasn't been implemented yet for supernodes. This is a possible feature to add to MultiNet for supernode aggregation and addresses this comment https://github.com/multinet-app/multimatrix/pull/120#discussion_r528043676_

**Comment by JackWilb** [comment]
This was not just for supergraphs, it was for sorting the matrix by a value in general.
