### ISSUE TITLE
Add toggle for edge directionality

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multimatrix#145]
Currently all edges are treated as non-driectional, and thus our matricies are all symmetric. We should add a toggle to fix that.

**Comment by gotdairyya** [comment]
I'm not sure we should treat this as a toggle but rather make this check for all networks

**Comment by JackWilb** [comment]
It could be something specified on upload, but the easiest way to solve this, at the scope of the visualization, is to just add a control toggle. We will likely want to support viewing the networks with and without directional edges anyway, even if a user could specify it on upload

**Comment by JackWilb** [comment]
I actually had a branch open for this on my local, so I'll tackle this once I'm done removing the class
