### ISSUE TITLE
Attribute label remains persistent

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#168]
This is a strange bug, to recreate it:

1. Select an attribute
2. Toggle directional edges
3. Remove selected attribute

After these steps, the label remains fixed on top. 

![image](https://user-images.githubusercontent.com/8480871/103674775-5d7c6e80-4f3c-11eb-894c-c0980f8bd048.png)

**Comment by JackWilb** [comment]
This is also happening when we do the aggregation. I'll need to take a look at the reactivity when the network changes
