### ISSUE TITLE
Dangerous Legend Code

### ISSUE THREAD

**Issue by mozartfish** [multinet-app/multimatrix#198]
This code looks dangerous. What if you have a legend with 5 cells and then it switches to a legend of 2 cells? We should remove the original legend before we remake the new one.

We should solve this in a follow up so we don't delay this PR. Please make an issue

_Originally posted by @JackWilb in https://github.com/multinet-app/multimatrix/pull/194#discussion_r572469669_

**Comment by JackWilb** [comment]
This is actually fine. The real problem is that we keep appending another `.legendLinear` when one already exists
