### ISSUE TITLE
Fix matrix load on subset 

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#265]
When loading a network that has been subsetted, the initial matrix visualization is flattened (everything drawn on one row)
Fixed after one interaction with the matrix
However, subsequent highlighting/hover interaction is wonky

**Comment by JackWilb** [comment]
I'm not sure that this is still affecting us. It appears to work on my instance with les mis and the twitter dataset. Can you still reproduce this @gotdairyya?

**Comment by gotdairyya** [comment]
We can close this, it's been fixed!
