### ISSUE TITLE
ConnectivityMatrix query autofill options

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#281]
the autocomplete options are computed from the network making it difficult to switch between queries

I'm considering creating store values as a solution 
@JackWilb what do you think of this as a solution?

![image](https://user-images.githubusercontent.com/8480871/123480838-2b30fd00-d5c0-11eb-902d-3876ba24f40b.png)

**Comment by JackWilb** [comment]
We talked on slack and I agree this is a good idea. There are a couple of benefits to this:

1. We're always able to query by edge conditions
1. We could query AQL to get all the values that are possible on networks that are too large. This improves filtering when we need to do a sample
