### ISSUE TITLE
[girder4] Investigate Oauth authentication quirks

### ISSUE THREAD

**Issue by naglepuff** [multinet-app/multimatrix#330]
Part of the porting multimatrix to girder4 (#216) was using `girder-oauth-client` to handle user authentication. This introduces some quirks that ought to be looked into.

Namely, if a user opens a network while not logged in, and then logs in, they will be redirected to the root URL, and not the network that they were previously looking at.

Also, opening multimatrix from the "main" client application (e.g. web.next.multinet.app), will not automatically log the user into multimatrix. Since they are both using the same backend, it might be possible for client applications to share credentials in some way. This might not be an issue if all client apps are in the same domain, however.

**Comment by JackWilb** [comment]
This is fixed
