### ISSUE TITLE
Add advanced querying to nodes

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#335]
Allow option to expand node querying in connectivity matrix to include OR/NOT*

Examples to illustrate each:

- I want to see flights from (Boston OR Chicago) to (NYC)
- I want to see flights from (San Jose NOT San Francisco) to (SLC)

If we add an AND to the query options it will have to be about another attribute, for example:

- I want to see connections between (Characters in chapter 1 AND women) to (Characters in chapter 3)

**Comment by curtislisle** [comment]
I apologize for behind behind on our query options needs.  That said, I'd like some clarification on one of the examples.  The second example (flights from SanJose NOT San Fran to SLC) confuses me.   I am assuming that the source node attribute (airport == "San Jose" ) would already be unique and would not include San Francisco-source flights.  

Am I confused or in this case are we looking for a way to exclude a subset instead like (from California, but NOT San Francisco)?
