### ISSUE TITLE
Reset label var on aggregation

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#369]
When switching between aggregations the label var should be updated to match the aggregation variable.

Currently it does not do that resulting in blank labels:
![image](https://user-images.githubusercontent.com/8480871/152713079-82bc24b6-84f4-4761-a1f6-30c13c7f2c74.png)

**Comment by gotdairyya** [comment]
This is closed, but @JackWilb I don't remember what PR closed it

**Comment by JackWilb** [comment]
Yeah, me neither 😂. I'll just close
