### ISSUE TITLE
Filter based on attribute value

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#50]
User can click the summary view of node attribute distribution and filter nodes based on values
![image](https://user-images.githubusercontent.com/8480871/80751936-eeff2b00-8ae7-11ea-9196-21acb447c924.png)
![image](https://user-images.githubusercontent.com/8480871/80751995-050ceb80-8ae8-11ea-85e9-a853c0483835.png)

**Comment by JackWilb** [comment]
Closed with the addition of lineup
