### ISSUE TITLE
Use a path length for connectivity (instead of hard-coded adjacency)

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multimatrix#51]
I'm sure this issue needs to be strategized a bit in terms of the user interface...

1. let user pick starting and end nodes
2. let user define maximum length of path

**Comment by waxlamp** [comment]
My idea had been to allow specifying a function to say whether two nodes are connected, but this restricted approach (give a path length, rather than a full-on function) is a better place to start.

**Comment by JackWilb** [comment]
This is closed with Derya's recent work
